# Site settings
title: Jeremy Gagon Web Developer
email: jergagon1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog for full stack web developer Jeremy Gagon.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jergagon1.github.io" # the base hostname & protocol for your site
twitter_username: jergagon1
github_username:  jergagon1

# Build settings
markdown: kramdown
